"use strict";
exports.__esModule = true;
exports.ADD_LOCAL_AUDIO = exports.SET_LOCAL_STOP = exports.SET_LOCAL_PAUSE = exports.SET_LOCAL_PLAY = exports.REMOVE_LOCAL_SONG = exports.SET_LOCAL_SONG = exports.TOGGLE_PLAYING = exports.SET_STOP = exports.SET_PAUSE = exports.SET_PLAY = exports.REMOVE_AUDIO = exports.SET_AUDIO = exports.REMOVE_HOWL = exports.SET_HOWL = void 0;
exports.SET_HOWL = 'SET_HOWL';
exports.REMOVE_HOWL = 'REMOVE_HOWL';
exports.SET_AUDIO = 'SET_AUDIO';
exports.REMOVE_AUDIO = 'REMOVE_AUDIO';
exports.SET_PLAY = 'SET_PLAY';
exports.SET_PAUSE = 'SET_PAUSE';
exports.SET_STOP = 'SET_STOP';
exports.TOGGLE_PLAYING = 'TOGGLE_PLAYING';
exports.SET_LOCAL_SONG = 'SET_LOCAL_SONG';
exports.REMOVE_LOCAL_SONG = 'REMOVE_LOCAL_SONG';
exports.SET_LOCAL_PLAY = 'SET_LOCAL_PLAY';
exports.SET_LOCAL_PAUSE = 'SET_LOCAL_PAUSE';
exports.SET_LOCAL_STOP = 'SET_LOCAL_STOP';
exports.ADD_LOCAL_AUDIO = 'ADD_LOCAL_AUDIO';
